### ISSUE TITLE
 Error when running the example

### ISSUE THREAD

**Issue by aukeheerdink** [PHOENIXcenter/pi-PrimeNovo#1]
When following the README example, I ran into an issue when running the example mgf file.

I used the following command: python -m PrimeNovo.PrimeNovo --mode=denovo --peak_path=data/bacillus.10k.mgf --model=data/model_massive.ckpt
And this gave me the following error:
```
Traceback (most recent call last):
  File "/home/xxxx/xxxx/envs/PrimeNovo2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxxx/xxxx/envs/PrimeNovo2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxxx/pi-PrimeNovo/PrimeNovo/PrimeNovo.py", line 211, in <module>
    main()
  File "/home/xxxx/xxxx/envs/PrimeNovo2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxxx/xxxx/envs/PrimeNovo2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/xxxx/xxxx/envs/PrimeNovo2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxxx/xxxx/envs/PrimeNovo2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/xxxx/pi-PrimeNovo/PrimeNovo/PrimeNovo.py", line 202, in main
    writer.save()
AttributeError: 'NoneType' object has no attribute 'save'
```

**Comment by wyattz23** [comment]
Sorry for this, we have replace the writer object with manual txt output file, so simply deleting this line of "writer.save()" fixes the error. We have fixed the error already, you can pull the GitHub code again and use it now!

Also, de novo mode now will output a **denovo.txt** file at your current directory, containing predictions results. Each line in this txt file has: (title (true label if given), model prediction, charge, confidence score (from 0-1)). Let us know if it works on your end!

**Comment by aukeheerdink** [comment]
Thanks for the quick resolve, works great now!
